[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "setuptools_scm[toml]>=6.2"]

[project]

name = "slamcore-aware-example-app"
version = "0.1.0"
description = "A client library for accessing Slamcore Aware - v0 "
dynamic = ["readme"]

authors = [{ name = "Slamcore", email = "support@slamcore.com" }]

license = { file = "LICENSE.md" }

classifiers = [
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "License :: Other/Proprietary License",
  "Operating System :: Unix",
]
requires-python = ">=3.10"

dependencies = [
  "httpx>=0.20.0,<0.29.0",
  "attrs>=22.2.0",
  "python-dateutil>=2.8.0",
  "websockets",
]

[tool.setuptools.exclude-package-data]
"*" = []

[tool.setuptools.package-data]
slamcore_aware_example_app = ["**"]

[tool.setuptools.dynamic]
readme = { file = ["README.md"] }

[tool.setuptools.packages.find]
include = ["slamcore_aware_example_app*"]

[project.scripts]
slamcore-aware-demo = "slamcore_aware_example_app.scripts.slamcore_aware_demo:parse_and_delegate_to_main"

[tool.ruff]
line-length = 95
target-version = "py310"
force-exclude = true
exclude = []

[tool.ruff.lint]
select = ["F", "I", "UP"]

[tool.ruff.lint.flake8-annotations]
# No need for -> None in __init__ methods
mypy-init-return = true

# vim: ft=toml
